### ISSUE TITLE
Tracking issue for all callbacks

### ISSUE THREAD

**Issue by haifeng-jin** [keras-team/keras#18475]
Here is a list of callbacks to be added:

- [x] [ModelCheckpoint](https://keras.io/api/callbacks/model_checkpoint)
- [x] [BackupAndRestore](https://keras.io/api/callbacks/backup_and_restore)
- [x] [TensorBoard](https://keras.io/api/callbacks/tensorboard)
- [x] [EarlyStopping](https://keras.io/api/callbacks/early_stopping)
- [x] [LearningRateScheduler](https://keras.io/api/callbacks/learning_rate_scheduler)
- [x] [ReduceLROnPlateau](https://keras.io/api/callbacks/reduce_lr_on_plateau)
- [x] [RemoteMonitor](https://keras.io/api/callbacks/remote_monitor)
- [x] [LambdaCallback](https://keras.io/api/callbacks/lambda_callback)
- [x] [TerminateOnNaN](https://keras.io/api/callbacks/terminate_on_nan)
- [x] [CSVLogger](https://keras.io/api/callbacks/csv_logger)
- [x] [ProgbarLogger](https://keras.io/api/callbacks/progbar_logger)

**Comment by sachinprasadhs** [comment]
@haifeng-jin , I think we can close this issue, since every task in the list is completed.

**Comment by haifeng-jin** [comment]
Yes. Thank you!
